#!/usr/bin/env python3
"""Generate sql/019_seed_event_merge_registry_v1.sql from
experiments/event_candidates/event_merge_prompt_v1.txt.

Mirrors gen_017.py: reads the prompt file verbatim, escapes it for a SQL
single-quoted literal (doubles single quotes), and emits one INSERT into
event_merge_prompts. prompt_id/prompt_name/prompt_version/schema_version
are fixed constants for this registry row -- v1 contract, not derived from
anything computed at runtime.
"""
import pathlib

PROMPT_PATH = pathlib.Path("experiments/event_candidates/event_merge_prompt_v1.txt")
OUT_PATH = pathlib.Path("sql/019_seed_event_merge_registry_v1.sql")

PROMPT_ID = 1
PROMPT_NAME = "event_merge"
PROMPT_VERSION = "v1"
SCHEMA_VERSION = "event-merge/1"


def main():
    prompt_text = PROMPT_PATH.read_text(encoding="utf-8")
    escaped = prompt_text.replace("'", "''")

    sql = (
        "-- 019_seed_event_merge_registry_v1.sql\n"
        "-- Auto-generated by gen_019.py from "
        "experiments/event_candidates/event_merge_prompt_v1.txt -- do not hand-edit.\n"
        "-- sql/018_add_event_merge.sql MUST be applied before this migration.\n\n"
        "INSERT INTO event_merge_prompts "
        "(prompt_id, prompt_name, prompt_version, schema_version, prompt_text)\n"
        "VALUES (\n"
        f"    {PROMPT_ID},\n"
        f"    '{PROMPT_NAME}',\n"
        f"    '{PROMPT_VERSION}',\n"
        f"    '{SCHEMA_VERSION}',\n"
        f"    '{escaped}'\n"
        ");\n"
    )

    OUT_PATH.write_text(sql, encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(sql)} bytes)")


if __name__ == "__main__":
    main()
