-- 004_seed_telegram_sources.sql
-- Контур 4 — Telegram-канали. source_type='telegram' навмисно (не 'web'):
-- це платформа джерела, спосіб доступу (web-preview зараз, MTProto пізніше)
-- відрізняється по url_or_handle-патерну ('https://t.me/s/%'), не по source_type.
-- ON CONFLICT DO UPDATE також лікує вже існуючі рядки, заведені раніше як 'web'.
INSERT INTO sources (name, url_or_handle, source_type, contour_id) VALUES
('Топор Live', 'https://t.me/s/topor', 'telegram', 4),
('РИА Новости (TG)', 'https://t.me/s/rian_ru', 'telegram', 4),
('Юрий Подоляка', 'https://t.me/s/yurasumy', 'telegram', 4),
('Mash', 'https://t.me/s/mash', 'telegram', 4),
('Readovka', 'https://t.me/s/readovkanews', 'telegram', 4),
('SHOT', 'https://t.me/s/shot_shot', 'telegram', 4),
('Операция Z: Военкоры Русской Весны', 'https://t.me/s/RVvoenkor', 'telegram', 4),
('Осторожно, новости', 'https://t.me/s/ostorozhno_novosti', 'telegram', 4),
('Минобороны России', 'https://t.me/s/mod_russia', 'telegram', 4),
('Рыбарь', 'https://t.me/s/rybar', 'telegram', 4),
('Kadyrov_95', 'https://t.me/s/RKadyrov_95', 'telegram', 4),
('Дмитрий Медведев', 'https://t.me/s/medvedev_telegram', 'telegram', 4),
('Baza', 'https://t.me/s/bazabazon', 'telegram', 4),
('Соловьев', 'https://t.me/s/SolovievLive', 'telegram', 4),
('Два майора', 'https://t.me/s/dva_majors', 'telegram', 4),
('WarGonzo', 'https://t.me/s/wargonzo', 'telegram', 4),
('Архангел Спецназа Z', 'https://t.me/s/rusich_army', 'telegram', 4),
('Анатолий Шарий', 'https://t.me/s/ASupremeSharij', 'telegram', 4),
('Сладков +', 'https://t.me/s/sladkov_plus', 'telegram', 4),
('RT на русском', 'https://t.me/s/rt_russian', 'telegram', 4),
('Свежести', 'https://t.me/s/svezhesti', 'telegram', 4),
('Colonelcassad', 'https://t.me/s/boris_rozhin', 'telegram', 4),
('Поддубный | Z | О!', 'https://t.me/s/epoddubny', 'telegram', 4),
('Повернутые на Z войне', 'https://t.me/s/voenacher', 'telegram', 4),
('Военный осведомитель', 'https://t.me/s/milinfolive', 'telegram', 4),
('Старше Эдды', 'https://t.me/s/vysokygovorit', 'telegram', 4),
('Kotsnews', 'https://t.me/s/sashakots', 'telegram', 4),
('Мария Захарова', 'https://t.me/s/MariaVladimirovnaZakharova', 'telegram', 4),
('Царьград ТВ', 'https://t.me/s/tsargradtv', 'telegram', 4),
('Vashy Novosti', 'https://t.me/s/news_forfree', 'telegram', 4),
('GREY ZONE', 'https://t.me/s/grey_zone', 'telegram', 4),
('Александр Ходаковский', 'https://t.me/s/aleksandr_skif', 'telegram', 4),
('РБК', 'https://t.me/s/rbc_news', 'telegram', 4),
('МИД России', 'https://t.me/s/MID_Russia', 'telegram', 4),
('ТАСС (TG)', 'https://t.me/s/tass_agency', 'telegram', 4),
('Маргарита Симоньян', 'https://t.me/s/margaritasimonyan', 'telegram', 4),
('Военкор Котенок Z', 'https://t.me/s/voenkorKotenok', 'telegram', 4),
('Голос Мордора', 'https://t.me/s/cgoth', 'telegram', 4),
('Вячеслав Володин', 'https://t.me/s/vv_volodin', 'telegram', 4),
('Силовики', 'https://t.me/s/siloviki', 'telegram', 4),
('Воин DV', 'https://t.me/s/voin_dv', 'telegram', 4),
('Записки ветерана', 'https://t.me/s/notes_veterans', 'telegram', 4),
('Блокнот Россия', 'https://t.me/s/bloknot_rossiya', 'telegram', 4),
('Dambiev', 'https://t.me/s/dambiev', 'telegram', 4),
('Комсомольская правда (TG)', 'https://t.me/s/truekpru', 'telegram', 4),
('Zergulio', 'https://t.me/s/SergeyKolyasnikov', 'telegram', 4),
('Олег Царев', 'https://t.me/s/olegtsarov', 'telegram', 4),
('REVERSE SIDE OF THE MEDAL', 'https://t.me/s/rsotmdivision', 'telegram', 4),
('Газета.Ru (TG)', 'https://t.me/s/gazetaru', 'telegram', 4),
('Вести', 'https://t.me/s/vesti_ru', 'telegram', 4),
('Владлен Татарский (архив)', 'https://t.me/s/vladlentatarsky', 'telegram', 4),
('Фронтовая птичка', 'https://t.me/s/frontbird', 'telegram', 4),
('Военная хроника', 'https://t.me/s/milchronicles', 'telegram', 4),
('Русский Тарантасъ', 'https://t.me/s/DmitriySteshin', 'telegram', 4),
('Московский Комсомолец', 'https://t.me/s/mk_ru', 'telegram', 4),
('Андрей Медведев', 'https://t.me/s/vityazeVA_live', 'telegram', 4),
('Zлой Пруф', 'https://t.me/s/zloy_pruf', 'telegram', 4),
('Специально для RT', 'https://t.me/s/rt_special', 'telegram', 4),
('Кремль. Новости', 'https://t.me/s/news_kremlin', 'telegram', 4),
('Alex Parker Returns', 'https://t.me/s/apwagner', 'telegram', 4),
('ГЕОПОЛИТИКА Z', 'https://t.me/s/geopolitika_z', 'telegram', 4),
('Северный Ветер', 'https://t.me/s/severny_veter_Z', 'telegram', 4),
('Сыны Отечества', 'https://t.me/s/syny_otechestva', 'telegram', 4),
('Військовий відділ РФ', 'https://t.me/s/mil_ru', 'telegram', 4),
('Политнавигатор', 'https://t.me/s/PolitNavigator', 'telegram', 4),
('Донбасс Медиа', 'https://t.me/s/donbass_media', 'telegram', 4),
('Торпеда Z', 'https://t.me/s/torpedaz', 'telegram', 4),
('Направленец по Украине', 'https://t.me/s/dirukr', 'telegram', 4),
('Роман Сапоньков', 'https://t.me/s/RSaponkov', 'telegram', 4),
('Канал вице-спикера ЛДПР', 'https://t.me/s/av_chernyshov', 'telegram', 4),
('Рыбарь на английском', 'https://t.me/s/rybar_in_english', 'telegram', 4),
('Егор Холмогоров', 'https://t.me/s/holmogorov_egor', 'telegram', 4)
ON CONFLICT (url_or_handle) DO UPDATE SET source_type = EXCLUDED.source_type, contour_id = EXCLUDED.contour_id;
